//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.BackOffice.Sale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTest
    {
        public int Id { get; set; }
        public decimal Giacu { get; set; }
        public decimal Giamoi { get; set; }
        public string iduser { get; set; }
    }



    public partial class sanphamexcel
    {
        public string STT { get; set; }
        public string MaSanPham { get; set; }
        public string SoLuong { get; set; }
        public string DonGia { get; set; }
        public int? WarehouseId { get; set; }
        public string Ten { get; set; }


    }
}
